# Generated by Django 5.0 on 2024-02-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_body_comment_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="body",
        ),
    ]
