# Generated by Django 5.0 on 2024-03-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
