# Generated by Django 5.0 on 2024-03-19 10:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_category_slug_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="post.title", max_length=255, verbose_name="image"
            ),
        ),
    ]
