# Generated by Django 5.0 on 2024-03-26 11:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
